version = "2"
generators = ["go", "go-grpc"]

# Control protoc include paths.
[includes]
  # defaults are "/usr/local/include" and "/usr/include", which don't exist on Windows.
  # override defaults to supress errors about non-existant directories.
  # after = []

# This section maps protobuf imports to Go packages.
[packages]
  # github.com/containerd/cgroups protofiles still list their go path as "github.com/containerd/cgroups/cgroup1/stats"
  "github.com/containerd/cgroups/v3/cgroup1/stats/metrics.proto" = "github.com/containerd/cgroups/v3/cgroup1/stats"

[[overrides]]
prefixes = [
  "github.com/Microsoft/hcsshim/internal/shimdiag",
  "github.com/Microsoft/hcsshim/internal/extendedtask",
  "github.com/Microsoft/hcsshim/internal/computeagent",
  "github.com/Microsoft/hcsshim/internal/ncproxyttrpc",
  "github.com/Microsoft/hcsshim/internal/vmservice",
  "github.com/Microsoft/hcsshim/internal/save",
]
generators = ["go", "go-ttrpc"]

[[overrides]]
prefixes = [
  "github.com/Microsoft/hcsshim/internal/lm/proto",
]
generators = ["go", "go-ttrpc"]
# Override the go package path for the generated code. This allows us to not need a go_package
# directive in the proto file itself, which is nice so we can share it with other projects easily.
parameters.go."Mgithub.com/Microsoft/hcsshim/internal/lm/proto/lm.proto" = '"github.com/Microsoft/hcsshim/internal/lm/proto;lmproto"'
parameters.go-ttrpc."Mgithub.com/Microsoft/hcsshim/internal/lm/proto/lm.proto" = '"github.com/Microsoft/hcsshim/internal/lm/proto;lmproto"'

[[overrides]]
prefixes = ["github.com/Microsoft/hcsshim/internal/state"]
generators = ["go"]